### ISSUE TITLE
Installation problem with py-perl5

### ISSUE THREAD

**Issue by Spiritdude** [Spiritdude/Prynt3r#1]
siamak reported (by email) following:
```
root@siaworkstation:/home/siamak/Prynt3r# make requirements
sudo apt install ser2net socat slic3r
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ser2net is already the newest version (4.3.4-2).
socat is already the newest version (1.7.4.1-3ubuntu5).
slic3r is already the newest version (1.3.0+dfsg1-5build1).
0 to upgrade, 0 to newly install, 0 to remove and 10 not to upgrade.
sudo apt install yagv libperl-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
yagv is already the newest version (0.4~20171211.r234ef16+dfsg-2).
libperl-dev is already the newest version (5.34.0-5ubuntu1.1).
0 to upgrade, 0 to newly install, 0 to remove and 10 not to upgrade.
pip3 install -r requirements.txt
Collecting trimesh
  Using cached trimesh-3.20.2-py3-none-any.whl (678 kB)
Collecting cython
  Using cached Cython-0.29.33-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
Collecting py-perl5
  Using cached py-perl5-2.0.0.tar.gz (28 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-wmu22ndb/py-perl5_a938cfb6d36647e5b847abcbcf6e0701/setup.py", line 26, in <module>
          from Cython.Distutils import build_ext
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make: *** [Makefile:17: requirements] Error 1
```

**Comment by Spiritdude** [comment]
Can you report which version of Ubuntu you run (20.04 or 22.04)?

**Comment by Spiritdude** [comment]
The relevant part is likely `ModuleNotFoundError: No module named 'Cython'`, so I'm not sure what's better to install Cython via `pip3` or `apt` - but as pip installs fails for you,  the apt is prefered:
```
sudo apt install cython3
```
and try again for `make requirements`, let me know.
